version: 1.0.{build}.0

environment:
  NuGetApiKey:
    secure: uNF4gY8KN67ODxKkGPBIz+5MDdf3MRtz4Vi+9McPhWYi4Z6YMQvOcTQRWZYd/N9b

install:
  - choco install -y wget
  - wget -q https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-dev-win-x64.1.0.1.exe
  - dotnet-dev-win-x64.1.0.1.exe /install /quiet /log dotnetinstall.log
  - ps: Push-AppveyorArtifact "dotnetinstall.log"

assembly_info:
  patch: true
  file: AndroidXml\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
  - cmd: cd AndroidXml
  - cmd: dotnet restore
  - cmd: dotnet build -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - ps: Push-AppveyorArtifact "bin\Release\AndroidXml.1.0.54-r$($env:APPVEYOR_BUILD_NUMBER).nupkg"

nuget:
  project_feed: true
  account_feed: true
