version: 1.0.{build}
build_script:
  - msbuild AndroidXml\AndroidXml.csproj /p:Configuration=Release /p:Platform=AnyCPU /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

on_success:
  - cmd: cd AndroidXml
  - cmd: nuget pack -Prop Configuration=Release 
  - cmd: appveyor PushArtifact AndroidXml.%APPVEYOR_BUILD_VERSION%.nupkg

nuget:
  project_feed: true
  account_feed: true
