version: 1.0.{build}.0

environment:
  NuGetApiKey:
    secure: uNF4gY8KN67ODxKkGPBIz+5MDdf3MRtz4Vi+9McPhWYi4Z6YMQvOcTQRWZYd/N9b

install:
  - choco install -y wget
  - wget -q https://download.microsoft.com/download/5/F/E/5FEB7E95-C643-48D5-8329-9D2C63676CE8/dotnet-dev-win-x64.1.0.0-rc4-004771.exe
  - dotnet-dev-win-x64.1.0.0-rc4-004771.exe /install /quiet /log dotnetinstall.log
  - ps: Push-AppveyorArtifact "dotnetinstall.log"

assembly_info:
  patch: true
  file: AndroidXml\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
  - cmd: cd AndroidXml
  - cmd: dotnet restore
  - cmd: dotnet build -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - ps: Push-AppveyorArtifact "bin\Release\AndroidXml.1.0.54-r$($env:APPVEYOR_BUILD_NUMBER).nupkg"
  - ps: Push-AppveyorArtifact "bin\Release\AndroidXml.1.0.54-r$($env:APPVEYOR_BUILD_NUMBER).symbols.nupkg"

nuget:
  project_feed: true
  account_feed: true
